version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.10
        environment:
          MIX_ENV: test
          DATABASE_URL: postgres://db:db@localhost:5432/db
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: db
          POSTGRES_DB: db
          POSTGRES_PASSWORD: db

    working_directory: ~/repo
    steps:
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - checkout
      - run: wget https://github.com/fhunleth/fwup/releases/download/v1.8.1/fwup_1.8.1_amd64.deb
      - run: sudo dpkg -i ./fwup_1.8.1_amd64.deb
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix compile
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix test
      - run: mix format --check-formatted
      - run: mix docs
      - run: mix hex.build
      - run: MIX_ENV=dev mix dialyzer --halt-exit-status
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
